version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: tcm
      POSTGRES_USER: tcm
      POSTGRES_PASSWORD: tcm
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'